# Generated by Django 5.0.2 on 2024-03-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_email_profile_name_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
