# Generated by Django 5.0.2 on 2024-03-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_property_photos_alter_property_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Property_for_renting',
        ),
        migrations.CreateModel(
            name='Property_on_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('property_type', models.CharField(choices=[('Rentals', 'Rentals'), ('Land', 'Land'), ('Home', 'Home')], max_length=50)),
                ('features', models.TextField()),
                ('photos', models.ImageField(null=True, upload_to='images/')),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('price', models.IntegerField()),
                ('contact', models.CharField(max_length=20)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
