# Generated by Django 5.0.2 on 2024-03-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_property_property_for_renting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_for_renting',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property_on_sale',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
