# Generated by Django 5.0.2 on 2024-03-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_property_for_renting_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_for_renting',
            old_name='size',
            new_name='house_type',
        ),
    ]
