# Generated by Django 5.0.2 on 2024-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_size_property_for_renting_house_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_for_renting',
            old_name='house_type',
            new_name='size',
        ),
    ]
