# Generated by Django 5.0.2 on 2024-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_property_for_renting_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_for_renting',
            name='photos',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property_for_renting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
