# Generated by Django 5.0.2 on 2024-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_property_for_renting_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_for_renting',
            name='size',
            field=models.CharField(choices=[('single room', 'single room'), ('Double room', 'Double room'), ('Bedsitter', 'Bedsitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedrooms', '2 Bedrooms'), ('3 Bedrooms', '3 Bedrooms'), ('4 Bedrooms', '4 Bedrooms'), ('5 Bedrooms', '5 Bedrooms'), ('Above 5 Bedrooms', 'Above 5 Bedrooms')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property_on_sale',
            name='photos',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property_on_sale',
            name='property_type',
            field=models.CharField(choices=[('Rentals', 'Rentals'), ('Land', 'Land'), ('House', 'House'), ('Vehicle', 'Vehicle')], max_length=50),
        ),
    ]
