# Generated by Django 5.0.2 on 2024-03-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_property_for_renting_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_on_sale',
            name='payment_process',
            field=models.TextField(null=True),
        ),
    ]
