# Generated by Django 5.0.2 on 2024-03-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_property_on_sale_payment_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_for_renting',
            name='pin_location',
            field=models.CharField(blank=True, default='Optional', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='property_on_sale',
            name='pin_location',
            field=models.CharField(blank=True, default='Optional', max_length=1000, null=True),
        ),
    ]
