# Generated by Django 5.0.2 on 2024-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_property_for_renting_pin_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_on_sale',
            name='pin_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
