# Generated by Django 5.0.2 on 2024-03-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_property_on_sale_pin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
