# Generated by Django 5.0.2 on 2024-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profile_id_number_profile_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_for_renting',
            name='id_photo_back',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property_for_renting',
            name='id_photo_front',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
