# Generated by Django 5.0.2 on 2024-03-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/images/defaultdp.jpg', null=True, upload_to='images/'),
        ),
    ]
