# Generated by Django 5.0.3 on 2024-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_property_for_renting_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_on_sale',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
    ]
