# Generated by Django 5.0.3 on 2024-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_property_on_sale_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='property_for_renting',
            name='photos',
        ),
        migrations.AddField(
            model_name='property_for_renting',
            name='photos',
            field=models.ManyToManyField(related_name='property_photos', to='app.propertyimage'),
        ),
    ]
