# Generated by Django 5.0.3 on 2024-03-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_propertyimage_remove_property_for_renting_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='property_renting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_photos', to='app.property_for_renting'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
