# Generated by Django 5.0.3 on 2024-03-13 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_property_for_renting_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_on_sale',
            old_name='photos',
            new_name='main_photo',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property_on_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_on_photos', to='app.property_on_sale'),
        ),
    ]
