# Generated by Django 5.0.3 on 2024-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_photos_property_on_sale_main_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_for_renting',
            name='garbage_fee',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property_for_renting',
            name='water_fee',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property_on_sale',
            name='deposit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
