# Generated by Django 5.0.3 on 2024-03-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_property_for_renting_garbage_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000, null=True)),
                ('mpesa_code', models.CharField(max_length=10, null=True)),
                ('date_and_time', models.CharField(max_length=1000, null=True)),
                ('amount', models.CharField(max_length=1000, null=True)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
