# Generated by Django 5.0.3 on 2024-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='MpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ResultCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ResultDesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='TransactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
