# Generated by Django 5.0.3 on 2024-03-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_subscription_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='person',
        ),
    ]
