# Generated by Django 5.0.3 on 2024-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_subscription_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
