# Generated by Django 5.0.3 on 2024-03-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_rentalsubscription_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
